swagger: '2.0'
info:
  version: '1.0'
  title: 'API unigrade - Documentação'
  description: >
    ## Visão Geral
      UniGrade é uma aplicação Android já desenvolvida anteriormente por alguns membros do grupo que tem como objetivo oferecer a alunos da UnB várias opções de grade horária a partir de alguns dados fornecidos pelo usuário.
      
      Aqui estão as rotas fornecidas pela api, feita em REST, detalhadas e explicadas

host: 'mwapi.herokuapp.com'
tags:
  - name: Discipline
    description: Discipline Controller
  - name: Class
    description: Class Controller
  - name: Course
    description: Course Controller
  - name: Habilitation
    description: Habilitation Controller
  - name: Search
    description: Search Controller
  - name: Timetable
    description: Timetable Controller

paths:
  /disciplines:
    get:
      tags:
        - 'Discipline'
      summary: 'retorna todas as disciplinas cadastradas'
      produces:
        - 'application/json'
      responses:
        200:
          description: 'OK'

  /discipline/{code}:
    get:
      tags:
        - 'Discipline'
      summary: 'retorna uma disciplina especifica'
      parameters:
        - in: 'path'
          name: 'code'
          type: 'integer'
          description: 'Código para a disciplina especifica'
          required: true
      produces:
        - 'application/json'
      responses:
        200:
          description: 'OK'

  /classes:
    get:
      tags:
        - 'Class'
      summary: 'retorna todas as turmas cadastradas'
      produces:
        - 'application/json'
      responses:
        200:
          description: 'OK'

  /classes/{code}:
    get:
      tags:
        - 'Class'
      summary: 'retorna todas as turmas de uma disciplina especifica'
      parameters:
        - in: 'path'
          name: 'code'
          type: 'integer'
          description: 'Código para uma disciplina especifica'
          required: true
      produces:
        - 'application/json'
      responses:
        200:
          description: 'OK'

  /classes/{code}/{name}:
    get:
      tags:
        - 'Class'
      summary: 'retorna uma turma especifica de um disciplina especifica'
      parameters:
        - in: 'path'
          name: 'code'
          type: 'integer'
          description: 'Código para uma disciplina especifica'
          required: true
        - in: 'path'
          name: 'name'
          type: 'string'
          description: 'nome identificador da turma especifica'
          required: true
      produces:
        - 'application/json'
      responses:
        200:
          description: 'OK'

  /courses:
    get:
      tags:
        - 'Course'
      summary: 'retorna todos os cursos cadastrados'
      produces:
        - 'application/json'
      responses:
        200:
          description: 'OK'

  /course/{campus}:
    get:
      tags:
        - 'Course'
      summary: 'retorna todos os cursos cadastrados em um campos especifico'
      parameters:
        - in: 'path'
          name: 'campus'
          type: 'integer'
          description: >
            codigo para um campus especifico

            #### 1 - Campus Darcy Ribeiro

            #### 2 - Campus Planaltina

            #### 3 - Campus Ceilândia

            #### 4 - Campus Gama

          enum: [1, 2, 3, 4]
          required: true
      produces:
        - 'application/json'
      responses:
        200:
          description: 'OK'

  /habilitations:
    get:
      tags:
        - 'Habilitation'
      summary: 'retorna todas as habilitações cadastradas'
      produces:
        - 'application/json'
      responses:
        200:
          description: 'OK'

  /habilitation/{code}:
    get:
      tags:
        - 'Habilitation'
      summary: 'retorna uma habilitação especifica'
      parameters:
        - in: 'path'
          name: 'code'
          type: 'integer'
          description: 'Código para uma habilitação especifica'
          required: true
      produces:
        - 'application/json'
      responses:
        200:
          description: 'OK'

  /search:
    post:
      tags:
        - 'Search'
      summary: 'Faz busca por matérias em todos os Campus'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'class or discipline'
          description: 'nome de professor, disciplina e código da disciplina para pesquisar na universidade'
          required: true
          schema:
            $ref: '#/definitions/search'
      responses:
        200:
          description: 'OK'

  /timetable:
    post:
      tags:
        - 'Timetable'
      summary: 'retorna possíveis grades com as matérias informadas'
      produces:
        - 'application/json'
      responses:
        200:
          description: 'OK'
    parameters:
      - in: 'body'
        name: 'disciplines'
        description: 'Lista de disciplinas desejadas no semestre'
        required: true
        schema:
          $ref: '#/definitions/timetable'

  /timetable/r:
    get:
      tags:
        - 'Timetable'
      summary: 'retorna uma grade com horarios aletórios '
      produces:
        - 'application/json'
      responses:
        200:
          description: 'OK'

definitions:
  search:
    type: 'object'
    properties:
      search:
        type: 'string'
        description: 'nome do professor, disciplina ou código da disciplina'
  timetable:
    type: 'array'
    items:
      type: 'object'
      properties:
        name:
          type: 'string'
          description: 'Turma da matéria'
        vacancies:
          type: 'number'
          description: 'número de vagas'
        teachers:
          type: 'array'
          items:
            type: 'string'
            description: 'nome dos professores desta matéria'
        meetings:
          type: 'array'
          items:
            type: 'object'
            properties:
              room:
                type: 'string'
                description: 'sala da matéria'
              day:
                type: 'string'
                description: 'dia da aula'
              init_hour:
                type: 'string'
                description: 'início da aula'
              final_hour:
                type: 'string'
                description: 'final da aula'
        discipline:
          type: 'string'
          description: 'nome da diciplina'
        shift:
          type: 'string'
          description: 'turno'
        campus:
          type: 'number'
        priority:
          type: 'integer'
          description: prioridade da matéria
